#==============================================================================
# Project: mbi 
#==============================================================================


#==============================================================================
# Directories
#==============================================================================

BASE_DIR     = .

EXE_DEST_DIR = $(BASE_DIR)/bin


#==============================================================================
# Project
#==============================================================================

DIST         = mbi_v1-ss
EXE          = mbi_ne

TARGET       = $(EXE)


OTHER_LIB    = -L$(BASE_DIR)/lib
OTHER_INC    = -I$(BASE_DIR)/include

INCS         = $(MATH_INC) $(OTHER_INC)
LIBS         = $(MATH_LIB) $(OTHER_LIB)
DEFS         =


SRCS = \
	d_util.c \
	genpop.c \
	model_WrightFisher.c \
	model_SexRatio.c \
	model_Autofecondation.c \
	model_CycleDemographique.c \
	model_Variance.c \
	main.c


OBJS = \
	d_util.o \
	genpop.o \
	model_WrightFisher.o \
	model_SexRatio.o \
	model_Autofecondation.o \
	model_CycleDemographique.o \
	model_Variance.o \
	main.o


HDRS = \
	d_util.h \
	genpop.h


DATA  = 



#==============================================================================
# Programs
#==============================================================================

CC           = gcc
CC_FLAGS     = -Wall -O $(DEFS) $(INCS)

MATH_LIB     = -lm
MATH_INC     =

CP           = cp
RM           = rm -f
RMDIR        = rm -rf
MKDIR        = mkdir -p



#==============================================================================
# Targets
#==============================================================================


#------------------------------------------------------------------------------
# all
#------------------------------------------------------------------------------
all: $(OBJS) $(TARGET)



#------------------------------------------------------------------------------
# install
#------------------------------------------------------------------------------
install: all
	$(CP) $(EXE) $(EXE_DEST_DIR)


#------------------------------------------------------------------------------
# remove
#------------------------------------------------------------------------------
remove:
	$(RM) $(EXE_DEST_DIR)/$(EXE)


#------------------------------------------------------------------------------
# clean
#------------------------------------------------------------------------------
clean:
	$(RM) $(OBJS) $(TARGET) $(DEP_FILE) *~ *.bak *.BAK *.exe *.EXE core



#==============================================================================
# Rules
#==============================================================================

#------------------------------------------------------------------------------
# C source file [.c] to object file [.o] compilation
#------------------------------------------------------------------------------

.SUFFIXES: .o .c

.c.o:
	$(CC) $(CC_FLAGS) -c $<



#------------------------------------------------------------------------------
# Exe
#------------------------------------------------------------------------------

$(EXE): $(OBJS)
	$(RM) $@
	$(CC) $(CC_FLAGS) -o $@ $(OBJS) $(LIBS)



#==============================================================================
# Depedencies
#==============================================================================

main.o: main.c genpop.h d_util.h

model_WrightFisher.o: model_WrightFisher.c genpop.h d_util.h

model_SexRatio.o: model_SexRatio.c genpop.h d_util.h

model_Autofecondation.o: model_Autofecondation.c genpop.h d_util.h

model_CycleDemographique.o: model_CycleDemographique.c genpop.h d_util.h

model_Variance.o: model_Variance.c genpop.h d_util.h

genpop.o: genpop.c genpop.h d_util.h

d_util.o: d_util.c d_util.h


